### ISSUE TITLE
Bug: While fetching: Undefined array key 0

### ISSUE THREAD

**Issue by tfk-kaare** [TromsFylkestrafikk/ragnarok-entur#4]
Got an error while fetching chunk 2024-04-23:

```
Undefined array key 0
Occured in /home/kaare/src/ragnarok/vendor/ragnarok/entur/src/Services/EnturSales.php(87)
- #0 /home/kaare/src/ragnarok/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
- #1 /home/kaare/src/ragnarok/vendor/ragnarok/entur/src/Services/EnturSales.php(87): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
- #2 /home/kaare/src/ragnarok/vendor/ragnarok/entur/src/Sinks/SinkEnturSales.php(36): Ragnarok\Entur\Services\EnturSales->download()
- #3 /home/kaare/src/ragnarok/app/Services/SinkHandler.php(117): Ragnarok\Entur\Sinks\SinkEnturSales->fetch()
- #4 /home/kaare/src/ragnarok/app/Services/SinkHandler.php(235): App\Services\SinkHandler->App\Services\{closure}()
- #5 /home/kaare/src/ragnarok/app/Services/SinkHandler.php(115): App\Services\SinkHandler->doRunOperation()
- #6 /home/kaare/src/ragnarok/app/Jobs/FetchChunk.php(41): App\Services\SinkHandler->fetchChunk()
- #7 /home/kaare/src/ragnarok/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\FetchChunk->handle()
- #8 /home/kaare/src/ragnarok/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
- #9 /home/kaare/src/ragnarok/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
- ...
```

**Comment by tfk-kaare** [comment]
This seems to be the case for all chunks prior to 2024-04-24

**Comment by jbtfk** [comment]
The API returns files based on when they are made available. Reports are not generated the first few days of the month. This requires some parsing to fetch correct file. Current parsing checks the filename for a timestamp. Looks like filenames prior to 2024-04-24 are formatted a little different.

[2024-06-14 10:18:18] local.DEBUG: [Sink entur-sales]: Chunk 2024-04-23: Fetching ...  
[2024-06-14 10:18:18] local.DEBUG: [EnTur CLEOS]: Requesting API token from EnTur.  
[2024-06-14 10:18:18] local.DEBUG: [EnTur CLEOS]: Token expires: 2024-06-15 10:18:18   
[2024-06-14 10:18:18] local.DEBUG: [EnTur CLEOS]: URL TO USE: https://api.entur.io/cleos-reporting/api/v1/partner-reports/report/next/content?templateId=1015&idAfter=0&firstOrderedDate=2024-04-23  
[2024-06-14 10:18:18] local.DEBUG: [EnTur CLEOS]: status: 200  
[2024-06-14 10:18:18] local.DEBUG: [EnTur CLEOS]: Fetching: 2024-04-23, filename:   
[2024-06-14 10:18:18] local.DEBUG: [EnTur CLEOS]: FILE: S-1_CSV2Troms_Fylkeskommune_Samferdsel_2024-04-24_2024042471471_v24.csv  
[2024-06-14 10:18:18] local.DEBUG: [EnTur CLEOS]: URL TO USE: https://api.entur.io/cleos-reporting/api/v1/partner-reports/report/next/content?templateId=1015&idAfter=566397&firstOrderedDate=2024-04-23  
[2024-06-14 10:18:19] local.DEBUG: [EnTur CLEOS]: Fetching: 2024-04-23, filename:   
[2024-06-14 10:18:19] local.DEBUG: [EnTur CLEOS]: FILE: S-1_CSV2S-1_CSV2_Troms_Fylkeskommune_Samferdsel_2024042371470_v24_v24.csv
